name: toast
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules