name: audio_handler
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  audio_session: ^0.1.25
  datatype_extensions:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: datatype_extensions
  ffmpeg_kit_flutter: ^6.0.3
  file_manager:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: file_manager
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  id3tag: ^0.2.0
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.11
  media_info: ^0.12.0
  path: ^1.9.1
  path_provider: ^2.1.5
  platform_adaptivity:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: platform_adaptivity
  shared_preferences: ^2.5.3

dev_dependencies:
  custom_lint: ^0.6.10
  flutter_lints: ^5.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules

flutter:
  assets:
    - assets/
