name: books_database_api
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  http: ^1.3.0
  intl: ^0.19.0
  platform_adaptivity:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: platform_adaptivity

flutter:
  assets:
    - images/