name: location_map
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  cached_network_image: ^3.4.0
  datatype_extensions:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: datatype_extensions
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  location: ^7.0.0
  platform_adaptivity:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: platform_adaptivity

dev_dependencies:
  custom_lint: ^0.6.8
  flutter_lints: ^5.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules