name: location_map
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  cached_network_image: ^3.4.1
  datatype_extensions:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: datatype_extensions
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  intl: ^0.20.2
  latlong2: ^0.9.1
  location: ^8.0.0
  platform_adaptivity:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: platform_adaptivity

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules