name: linter_rules
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  analyzer: ^7.4.5
  analyzer_plugin: ^0.13.1
  custom_lint_builder: ^0.7.5
  pub_semver: ^2.2.0

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0