name: linter_rules
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.8
  pub_semver: ^2.1.4

dev_dependencies:
  custom_lint: ^0.6.8
  flutter_lints: ^5.0.0