name: linter_rules
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  analyzer: ^6.11.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.10
  pub_semver: ^2.2.0

dev_dependencies:
  custom_lint: ^0.6.10
  flutter_lints: ^5.0.0