name: file_manager
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  archive: ^3.5.0
  csv: ^6.0.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  toast:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: toast

dev_dependencies:
  custom_lint: ^0.6.0
  flutter_lints: ^4.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules
