name: file_manager
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  archive: ^3.6.1
  csv: ^6.0.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  toast:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: toast

dev_dependencies:
  custom_lint: ^0.6.10
  flutter_lints: ^5.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules
