name: file_manager
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  archive: ^4.0.7
  csv: ^6.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  toast:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: toast

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules
