name: notification
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  awesome_notifications: ^0.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules