name: circle_around_animation
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform_adaptivity:
    git:
      url: git@gitlab.ub.uni-bielefeld.de:bi-vital/flutter_packages.git
      path: platform_adaptivity
  widget_mask: ^1.0.0+0

dev_dependencies:
  custom_lint: ^0.6.0
  flutter_lints: ^4.0.0
  linter_rules:
    git:
      url: git@gitlab.ub.uni-bielefeld.de:bi-vital/flutter_packages.git
      path: linter_rules