name: settings_section
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  datatype_extensions:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: datatype_extensions
  flutter:
    sdk: flutter
  platform_adaptivity:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: platform_adaptivity
  shared_preferences: ^2.5.3

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules