/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

@staticIconProvider
abstract final class AppIcons {
  const AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = 'platform_adaptivity';

  static const IconData arts = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atom = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binocularscupertino = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binocularsfillcupertino = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binocularsfillmaterial = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binocularsmaterial = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bivital = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubbleleft = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buground = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData continuouspage = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData continuouspagealt = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData csv = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dayandnight = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dayandnightoutlined = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropdownup = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ecgheartcupertino = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ecgheartmaterial = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entertainment = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData externallink = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritefill = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoriteslash = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoriteslashfill = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figure_2_and_child_holdinghands = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figurerun = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward5material = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward10material = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward15material = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward30material = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward45material = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward60material = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward75material = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward90material = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuelpumpfill = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gearfill = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gobackward5 = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goforward5 = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontalscrolling = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imagesstack = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listbulletfill = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mp3 = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nobug = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nosignal = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagebypage = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagebypagealt = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paintpalette = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pray = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prize = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rabbitfill = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData racing = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay5material = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay10material = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay15material = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay30material = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay45material = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay60material = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay75material = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay90material = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsfill = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperaturesensor = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tire = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tortoisefill = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tragedy = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verticalscrolling = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vitalsigns = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waveformpathecgrectangle = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zip = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
