name: datatype_extensions
publish_to: none

environment:
  sdk: '>=3.0.0'

dependencies:
  basics: ^0.10.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  platform_adaptivity:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: platform_adaptivity

dev_dependencies:
  custom_lint: ^0.6.8
  flutter_lints: ^5.0.0
  linter_rules:
    git:
      url: git@github.com:LathDevers/flutter_packages.git
      path: linter_rules