name: platform_adaptivity
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

dependencies:
  datatype_extensions:
    git:
      url: git@gitlab.ub.uni-bielefeld.de:bi-vital/flutter_packages.git
      path: datatype_extensions
  dropdown_button2: ^2.3.9
  fluent_ui: ^4.8.6
  fluentui_system_icons: ^1.1.229
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  pull_down_button: ^0.9.3

flutter:
  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf

dev_dependencies:
  custom_lint: ^0.6.0
  flutter_lints: ^3.0.1
  linter_rules:
    git:
      url: git@gitlab.ub.uni-bielefeld.de:bi-vital/flutter_packages.git
      path: linter_rules